"""
CNN/demo/inference.py

Loads the INT8-quantized CNN ONNX model and preprocessed dataset once at startup.
Provides run_inference(resources, window_idx) for the Streamlit app.

Scores are computed live via a single ONNX forward pass (~1-10 ms on CPU),
so no pre-computed CSV is required. The detection threshold comes from
cnn_deploy_meta.npz (generated by evaluate_cnn.py on the training machine).
"""

from __future__ import annotations

import numpy as np
from pathlib import Path

# Resolve paths relative to the project root (CNN/demo/ -> CNN/ -> project root)
_DEMO_DIR    = Path(__file__).parent
_CNN_DIR     = _DEMO_DIR.parent
PROJECT_ROOT = _CNN_DIR.parent

ONNX_PATH = PROJECT_ROOT / "CNN/experiments/results/cnn_quantized.onnx"
META_PATH = PROJECT_ROOT / "CNN/experiments/results/cnn_deploy_meta.npz"
NPZ_PATH  = PROJECT_ROOT / "data/processed/preprocessed.npz"


def load_resources() -> dict:
    """
    Load ONNX session, memory-mapped dataset, vocab, and threshold.
    Called once at startup and cached by Streamlit (@st.cache_resource).
    """
    try:
        import onnxruntime as ort
    except ImportError as exc:
        raise RuntimeError(
            "onnxruntime not found. Activate the Ryzen AI conda env:\n"
            "  conda activate ryzen-ai-1.7.0"
        ) from exc

    if not ONNX_PATH.exists():
        raise FileNotFoundError(
            f"Quantized model not found: {ONNX_PATH}\n"
            "Run: python CNN/quantize_cnn.py"
        )
    if not NPZ_PATH.exists():
        raise FileNotFoundError(
            f"Preprocessed data not found: {NPZ_PATH}\n"
            "Run: python scripts/preprocess_data.py"
        )
    if not META_PATH.exists():
        raise FileNotFoundError(
            f"Deployment metadata not found: {META_PATH}\n"
            "Run: python CNN/evaluate_cnn.py on the training machine, "
            "then copy CNN/experiments/results/cnn_deploy_meta.npz here."
        )

    # CPU session — reliable for demo; NPU requires the full Ryzen AI driver stack
    sess = ort.InferenceSession(
        str(ONNX_PATH),
        providers=["CPUExecutionProvider"],
    )

    # Memory-map the dataset — only accessed windows are paged into RAM
    bundle = np.load(str(NPZ_PATH), allow_pickle=True, mmap_mode="r")
    X_num = bundle["X_num"]               # (N, 10, 21) float32, memory-mapped
    X_cat = bundle["X_cat"]               # (N, 10, 3)  int64, memory-mapped
    y_seq = np.array(bundle["y_seq"])     # (N,) int64  — small, copy into RAM

    # Feature names stored by preprocess_data.py
    num_features = list(bundle["num_features"])   # 21 numeric feature names
    cat_features = list(bundle["cat_features"])   # ["Sport", "Dport", "Proto"]

    # Categorical vocabularies: stored as np.array([dict], dtype=object)
    sport_vocab = bundle["sport_vocab"][0]   # value -> id
    dport_vocab = bundle["dport_vocab"][0]
    proto_vocab = bundle["proto_vocab"][0]
    inv_vocabs = [
        {v: k for k, v in sport_vocab.items()},
        {v: k for k, v in dport_vocab.items()},
        {v: k for k, v in proto_vocab.items()},
    ]

    # Detection threshold from evaluation on training machine
    meta = np.load(str(META_PATH), allow_pickle=True)
    threshold = float(meta["threshold"])

    return {
        "sess":         sess,
        "X_num":        X_num,
        "X_cat":        X_cat,
        "y_seq":        y_seq,
        "num_features": num_features,
        "cat_features": cat_features,
        "inv_vocabs":   inv_vocabs,
        "threshold":    threshold,
    }


def run_inference(resources: dict, window_idx: int) -> dict:
    """
    Run a single ONNX forward pass and return everything needed for visualization.

    Returns
    -------
    dict with keys:
      x_num_raw     (10, 21) – normalized numeric input
      x_hat_num     (10, 21) – CNN reconstruction
      x_cat_decoded list[dict] – human-readable categorical values per flow
      per_feat_err  (21,) – per-feature MSE between input and reconstruction
      anomaly_score float – mean MSE (= anomaly score)
      threshold     float – detection threshold (99th percentile of normal scores)
      is_attack     bool  – True if anomaly_score > threshold
      ground_truth  int   – 0=normal, 1=attack (from dataset labels)
      window_idx    int
    """
    sess        = resources["sess"]
    X_num       = resources["X_num"]
    X_cat       = resources["X_cat"]
    y_seq       = resources["y_seq"]
    threshold   = resources["threshold"]
    inv_vocabs  = resources["inv_vocabs"]
    cat_features = resources["cat_features"]

    # Slice single window from memory-mapped arrays (copies ~2 KB into RAM)
    x_num = np.array(X_num[window_idx : window_idx + 1], dtype=np.float32)  # (1, 10, 21)
    x_cat = np.array(X_cat[window_idx : window_idx + 1], dtype=np.int64)    # (1, 10, 3)

    # ONNX forward pass — model outputs x_hat_num only (latent stripped at export)
    x_hat_num = sess.run(None, {"x_num": x_num, "x_cat": x_cat})[0]  # (1, 10, 21)

    # Anomaly score: mean MSE across all timesteps and features
    per_feat_err  = ((x_hat_num[0] - x_num[0]) ** 2).mean(axis=0)    # (21,)
    anomaly_score = float(per_feat_err.mean())

    # Decode categorical IDs back to human-readable values
    x_cat_decoded = []
    for t in range(x_cat.shape[1]):
        row = {}
        for fi, (fname, inv_v) in enumerate(zip(cat_features, inv_vocabs)):
            cat_id = int(x_cat[0, t, fi])
            row[fname] = inv_v.get(cat_id, f"UNK({cat_id})")
        x_cat_decoded.append(row)

    return {
        "x_num_raw":     x_num[0],          # (10, 21)
        "x_hat_num":     x_hat_num[0],      # (10, 21)
        "x_cat_decoded": x_cat_decoded,     # list[dict], len=10
        "per_feat_err":  per_feat_err,      # (21,)
        "anomaly_score": anomaly_score,
        "threshold":     threshold,
        "is_attack":     anomaly_score > threshold,
        "ground_truth":  int(y_seq[window_idx]),
        "window_idx":    window_idx,
    }
